// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateOutboxEvent(ctx context.Context, arg *CreateOutboxEventParams) (*OutboxEvent, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetUnpublishedEvents(ctx context.Context, limit int32) ([]*OutboxEvent, error)
	GetUser(ctx context.Context, id int64) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	MarkEventAsPublished(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
